In [23]:
import talib as ta
import numpy as np
import pandas as pd
import yfinance as yf
from talib import MA_Type
from datetime import date
from talib import abstract

## DOWNLOAD HISTORICAL STOCK DATA FOR INFOSYS

In [24]:
ticker = 'INFY'
start_time = '2021-01-02'
today = date.today()
end_time = today.strftime("%Y-%m-%d")

In [25]:
df = pd.DataFrame()
df = yf.download(ticker, start = start_time, end = end_time)

df.head()

[*********************100%***********************]  1 of 1 completed

                 Open       High        Low      Close  Adj Close    Volume
Date
2021-01-04  17.389999  17.430000  17.059999  17.250000  17.071890  12597600
2021-01-05  17.320000  17.670000  17.320000  17.650000  17.467758   8109900
2021-01-06  17.400000  17.790001  17.340000  17.730000  17.546932   9136300
2021-01-07  17.360001  17.549999  17.260000  17.549999  17.368792  10272000
2021-01-08  18.070000  18.610001  18.020000  18.590000  18.398054  17802400

In [26]:
df =  df.rename(columns={'Open': 'open', 'High': 'high', 'Low': 'low', 'Adj Close': 'close', 'Volume': 'volume'})
df = df.drop(['Close'], axis='columns')
df

                 open       high        low      close    volume
Date
2021-01-04  17.389999  17.430000  17.059999  17.071890  12597600
2021-01-05  17.320000  17.670000  17.320000  17.467758   8109900
2021-01-06  17.400000  17.790001  17.340000  17.546932   9136300
2021-01-07  17.360001  17.549999  17.260000  17.368792  10272000
2021-01-08  18.070000  18.610001  18.020000  18.398054  17802400
...               ...        ...        ...        ...       ...
2021-06-02  19.090000  19.290001  19.080000  19.290001   6886400
2021-06-03  19.180000  19.260000  19.090000  19.139999   5827400
2021-06-04  19.209999  19.290001  19.080000  19.290001   6484000
2021-06-07  19.290001  19.480000  19.219999  19.400000  10765100
2021-06-08  19.580000  19.650000  19.389999  19.500000   7916900

[108 rows x 5 columns]

## CALCULATE MOVING AVERAGES

In [27]:
df['SMA'] = abstract.SMA(df, 20)
df['WMA'] = abstract.WMA(df, 20)
df['EMA'] = abstract.EMA(df, 20)
df['DEMA'] = abstract.DEMA(df, 20)
df['TEMA'] = abstract.TEMA(df, 20)

df

,open,high,low,close,volume,SMA,WMA,EMA,DEMA,TEMA
Date,,,,,,,,,,
2021-01-04,17.389999,17.430000,17.059999,17.071890,12597600,NaN,NaN,NaN,NaN,NaN
2021-01-05,17.320000,17.670000,17.320000,17.467758,8109900,NaN,NaN,NaN,NaN,NaN
2021-01-06,17.400000,17.790001,17.340000,17.546932,9136300,NaN,NaN,NaN,NaN,NaN
2021-01-07,17.360001,17.549999,17.260000,17.368792,10272000,NaN,NaN,NaN,NaN,NaN
2021-01-08,18.070000,18.610001,18.020000,18.398054,17802400,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2021-06-02,19.090000,19.290001,19.080000,19.290001,6886400,18.431409,18.662140,18.608480,18.951608,19.221126
2021-06-03,19.180000,19.260000,19.090000,19.139999,5827400,18.483352,18.729625,18.659101,19.015350,19.271071
2021-06-04,19.209999,19.290001,19.080000,19.290001,6484000,18.527454,18.806449,18.719187,19.095870,19.345726
2021-06-07,19.290001,19.480000,19.219999,19.400000,10765100,18.587943,18.889549,18.784026,19.183499,19.430178
2021-06-08,19.580000,19.650000,19.389999,19.500000,7916900,18.654422,18.976411,18.852214,19.275336,19.519918

## CALCULATE MOMENTUM INDICATORS

In [28]:
df['RSI'] = abstract.RSI(df, 14)

temp = abstract.MACD(df, fastperiod=12, slowperiod=26)
df['MACD'] = temp['macd']
df['MACD Signal'] = temp['macdsignal']

df['ADX'] = abstract.ADX(df, 14)
df['DI+'] = abstract.PLUS_DI(df, 14)
df['DI-'] = abstract.MINUS_DI(df, 14)

temp = abstract.STOCHF(df, fastk_period=14)
df['Stochastic Oscillator'] = temp['fastk']

df['Williams %R'] = abstract.WILLR(df, 14)

df

,open,high,low,close,volume,SMA,WMA,EMA,DEMA,TEMA,RSI,MACD,MACD Signal,ADX,DI+,DI-,Stochastic Oscillator,Williams %R
Date,,,,,,,,,,,,,,,,,,
2021-01-04,17.389999,17.430000,17.059999,17.071890,12597600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-01-05,17.320000,17.670000,17.320000,17.467758,8109900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-01-06,17.400000,17.790001,17.340000,17.546932,9136300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-01-07,17.360001,17.549999,17.260000,17.368792,10272000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-01-08,18.070000,18.610001,18.020000,18.398054,17802400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-02,19.090000,19.290001,19.080000,19.290001,6886400,18.431409,18.662140,18.608480,18.951608,19.221126,68.053777,0.295160,0.160851,16.484004,26.324064,17.279934,88.484929,-11.515071
2021-06-03,19.180000,19.260000,19.090000,19.139999,5827400,18.483352,18.729625,18.659101,19.015350,19.271071,63.636985,0.299045,0.188490,16.788112,25.279769,16.594426,77.333323,-22.666677
2021-06-04,19.209999,19.290001,19.080000,19.290001,6484000,18.527454,18.806449,18.719187,19.095870,19.345726,66.012504,0.310647,0.212921,17.155833,24.807777,15.881985,86.231975,-13.768025
2021-06-07,19.290001,19.480000,19.219999,19.400000,10765100,18.587943,18.889549,18.784026,19.183499,19.430178,67.679934,0.324971,0.235331,18.017091,27.421222,15.022073,93.846156,-6.153844
2021-06-08,19.580000,19.650000,19.389999,19.500000,7916900,18.654422,18.976411,18.852214,19.275336,19.519918,69.161172,0.340468,0.256358,19.233571,29.512858,14.194415,89.795940,-10.204060

## EXTRACT CLOSING PRICE OF OTHER TICKERS

In [29]:
temp = yf.download('TCS', start = start_time, end = end_time)
df['TCS Close'] = temp['Adj Close']

[*********************100%***********************]  1 of 1 completed

In [30]:
df

,open,high,low,close,volume,SMA,WMA,EMA,DEMA,TEMA,RSI,MACD,MACD Signal,ADX,DI+,DI-,Stochastic Oscillator,Williams %R,TCS Close
Date,,,,,,,,,,,,,,,,,,,
2021-01-04,17.389999,17.430000,17.059999,17.071890,12597600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.72
2021-01-05,17.320000,17.670000,17.320000,17.467758,8109900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.79
2021-01-06,17.400000,17.790001,17.340000,17.546932,9136300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.07
2021-01-07,17.360001,17.549999,17.260000,17.368792,10272000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.35
2021-01-08,18.070000,18.610001,18.020000,18.398054,17802400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-02,19.090000,19.290001,19.080000,19.290001,6886400,18.431409,18.662140,18.608480,18.951608,19.221126,68.053777,0.295160,0.160851,16.484004,26.324064,17.279934,88.484929,-11.515071,13.46
2021-06-03,19.180000,19.260000,19.090000,19.139999,5827400,18.483352,18.729625,18.659101,19.015350,19.271071,63.636985,0.299045,0.188490,16.788112,25.279769,16.594426,77.333323,-22.666677,12.99
2021-06-04,19.209999,19.290001,19.080000,19.290001,6484000,18.527454,18.806449,18.719187,19.095870,19.345726,66.012504,0.310647,0.212921,17.155833,24.807777,15.881985,86.231975,-13.768025,13.05
2021-06-07,19.290001,19.480000,19.219999,19.400000,10765100,18.587943,18.889549,18.784026,19.183499,19.430178,67.679934,0.324971,0.235331,18.017091,27.421222,15.022073,93.846156,-6.153844,13.50
2021-06-08,19.580000,19.650000,19.389999,19.500000,7916900,18.654422,18.976411,18.852214,19.275336,19.519918,69.161172,0.340468,0.256358,19.233571,29.512858,14.194415,89.795940,-10.204060,13.86

In [31]:
df =  df.rename(columns={'open': 'Open', 'high': 'High', 'low': 'Low', 'close': 'Target', 'volume': 'Volume'})
df

,Open,High,Low,Target,Volume,SMA,WMA,EMA,DEMA,TEMA,RSI,MACD,MACD Signal,ADX,DI+,DI-,Stochastic Oscillator,Williams %R,TCS Close
Date,,,,,,,,,,,,,,,,,,,
2021-01-04,17.389999,17.430000,17.059999,17.071890,12597600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.72
2021-01-05,17.320000,17.670000,17.320000,17.467758,8109900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.79
2021-01-06,17.400000,17.790001,17.340000,17.546932,9136300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.07
2021-01-07,17.360001,17.549999,17.260000,17.368792,10272000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.35
2021-01-08,18.070000,18.610001,18.020000,18.398054,17802400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-02,19.090000,19.290001,19.080000,19.290001,6886400,18.431409,18.662140,18.608480,18.951608,19.221126,68.053777,0.295160,0.160851,16.484004,26.324064,17.279934,88.484929,-11.515071,13.46
2021-06-03,19.180000,19.260000,19.090000,19.139999,5827400,18.483352,18.729625,18.659101,19.015350,19.271071,63.636985,0.299045,0.188490,16.788112,25.279769,16.594426,77.333323,-22.666677,12.99
2021-06-04,19.209999,19.290001,19.080000,19.290001,6484000,18.527454,18.806449,18.719187,19.095870,19.345726,66.012504,0.310647,0.212921,17.155833,24.807777,15.881985,86.231975,-13.768025,13.05
2021-06-07,19.290001,19.480000,19.219999,19.400000,10765100,18.587943,18.889549,18.784026,19.183499,19.430178,67.679934,0.324971,0.235331,18.017091,27.421222,15.022073,93.846156,-6.153844,13.50
2021-06-08,19.580000,19.650000,19.389999,19.500000,7916900,18.654422,18.976411,18.852214,19.275336,19.519918,69.161172,0.340468,0.256358,19.233571,29.512858,14.194415,89.795940,-10.204060,13.86

## CALCULATE RETURNS OF TARGET VARIABLE AND OTHER TICKERS

In [32]:
df['Returns Target'] = (df['Target']/df['Target'].shift(1)) - 1

In [34]:
df['Returns TCS'] = (df['TCS Close']/df['TCS Close'].shift(1)) - 1

In [35]:
df

,Open,High,Low,Target,Volume,SMA,WMA,EMA,DEMA,TEMA,...,MACD,MACD Signal,ADX,DI+,DI-,Stochastic Oscillator,Williams %R,TCS Close,Returns Target,Returns TCS
Date,,,,,,,,,,,,,,,,,,,,,
2021-01-04,17.389999,17.430000,17.059999,17.071890,12597600,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.72,NaN,NaN
2021-01-05,17.320000,17.670000,17.320000,17.467758,8109900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.79,0.023188,0.007202
2021-01-06,17.400000,17.790001,17.340000,17.546932,9136300,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.07,0.004533,0.130746
2021-01-07,17.360001,17.549999,17.260000,17.368792,10272000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.35,-0.010152,0.025294
2021-01-08,18.070000,18.610001,18.020000,18.398054,17802400,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.36,0.059259,0.000881
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-02,19.090000,19.290001,19.080000,19.290001,6886400,18.431409,18.662140,18.608480,18.951608,19.221126,...,0.295160,0.160851,16.484004,26.324064,17.279934,88.484929,-11.515071,13.46,0.001038,0.018154
2021-06-03,19.180000,19.260000,19.090000,19.139999,5827400,18.483352,18.729625,18.659101,19.015350,19.271071,...,0.299045,0.188490,16.788112,25.279769,16.594426,77.333323,-22.666677,12.99,-0.007776,-0.034918
2021-06-04,19.209999,19.290001,19.080000,19.290001,6484000,18.527454,18.806449,18.719187,19.095870,19.345726,...,0.310647,0.212921,17.155833,24.807777,15.881985,86.231975,-13.768025,13.05,0.007837,0.004619
2021-06-07,19.290001,19.480000,19.219999,19.400000,10765100,18.587943,18.889549,18.784026,19.183499,19.430178,...,0.324971,0.235331,18.017091,27.421222,15.022073,93.846156,-6.153844,13.50,0.005702,0.034483
2021-06-08,19.580000,19.650000,19.389999,19.500000,7916900,18.654422,18.976411,18.852214,19.275336,19.519918,...,0.340468,0.256358,19.233571,29.512858,14.194415,89.795940,-10.204060,13.86,0.005155,0.026667

## CALCULATE VOLUME CHANGE

In [36]:
df['Volume Change'] = df['Volume']/df['Volume'].shift(1)

In [37]:
df

,Open,High,Low,Target,Volume,SMA,WMA,EMA,DEMA,TEMA,...,MACD Signal,ADX,DI+,DI-,Stochastic Oscillator,Williams %R,TCS Close,Returns Target,Returns TCS,Volume Change
Date,,,,,,,,,,,,,,,,,,,,,
2021-01-04,17.389999,17.430000,17.059999,17.071890,12597600,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,9.72,NaN,NaN,NaN
2021-01-05,17.320000,17.670000,17.320000,17.467758,8109900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,9.79,0.023188,0.007202,0.643765
2021-01-06,17.400000,17.790001,17.340000,17.546932,9136300,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,11.07,0.004533,0.130746,1.126561
2021-01-07,17.360001,17.549999,17.260000,17.368792,10272000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,11.35,-0.010152,0.025294,1.124306
2021-01-08,18.070000,18.610001,18.020000,18.398054,17802400,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,11.36,0.059259,0.000881,1.733100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-02,19.090000,19.290001,19.080000,19.290001,6886400,18.431409,18.662140,18.608480,18.951608,19.221126,...,0.160851,16.484004,26.324064,17.279934,88.484929,-11.515071,13.46,0.001038,0.018154,0.756141
2021-06-03,19.180000,19.260000,19.090000,19.139999,5827400,18.483352,18.729625,18.659101,19.015350,19.271071,...,0.188490,16.788112,25.279769,16.594426,77.333323,-22.666677,12.99,-0.007776,-0.034918,0.846219
2021-06-04,19.209999,19.290001,19.080000,19.290001,6484000,18.527454,18.806449,18.719187,19.095870,19.345726,...,0.212921,17.155833,24.807777,15.881985,86.231975,-13.768025,13.05,0.007837,0.004619,1.112675
2021-06-07,19.290001,19.480000,19.219999,19.400000,10765100,18.587943,18.889549,18.784026,19.183499,19.430178,...,0.235331,18.017091,27.421222,15.022073,93.846156,-6.153844,13.50,0.005702,0.034483,1.660256
2021-06-08,19.580000,19.650000,19.389999,19.500000,7916900,18.654422,18.976411,18.852214,19.275336,19.519918,...,0.256358,19.233571,29.512858,14.194415,89.795940,-10.204060,13.86,0.005155,0.026667,0.735423