In [124]:
import talib as ta
import numpy as np
import pandas as pd
import yfinance as yf
from talib import MA_Type
from datetime import date
from talib import abstract

## DOWNLOAD HISTORICAL STOCK DATA FOR APPLE

In [125]:
ticker = 'AAPL'
start_time = '2020-01-02'
today = date.today()
end_time = today.strftime("%Y-%m-%d")

In [126]:
df = pd.DataFrame()
df = yf.download(ticker, start = start_time, end = end_time)

df.head()

[*********************100%***********************]  1 of 1 completed

                 Open       High        Low      Close  Adj Close     Volume
Date
2020-01-02  74.059998  75.150002  73.797501  75.087502  74.207466  135480400
2020-01-03  74.287498  75.144997  74.125000  74.357498  73.486023  146322800
2020-01-06  73.447502  74.989998  73.187500  74.949997  74.071579  118387200
2020-01-07  74.959999  75.224998  74.370003  74.597504  73.723213  108872000
2020-01-08  74.290001  76.110001  74.290001  75.797501  74.909149  132079200

In [127]:
df =  df.rename(columns={'Open': 'open', 'High': 'high', 'Low': 'low', 'Adj Close': 'close', 'Volume': 'volume'})
df = df.drop(['Close'], axis='columns')
df

                  open        high         low       close     volume
Date
2020-01-02   74.059998   75.150002   73.797501   74.207466  135480400
2020-01-03   74.287498   75.144997   74.125000   73.486023  146322800
2020-01-06   73.447502   74.989998   73.187500   74.071579  118387200
2020-01-07   74.959999   75.224998   74.370003   73.723213  108872000
2020-01-08   74.290001   76.110001   74.290001   74.909149  132079200
...                ...         ...         ...         ...        ...
2021-05-28  125.570000  125.800003  124.550003  124.610001   71311100
2021-06-01  125.080002  125.349998  123.940002  124.279999   67637100
2021-06-02  124.279999  125.239998  124.050003  125.059998   59278900
2021-06-03  124.680000  124.849998  123.129997  123.540001   76229200
2021-06-04  124.070000  126.160004  123.849998  125.889999   75087300

[359 rows x 5 columns]

## CALCULATE MOVING AVERAGES

In [128]:
df['SMA'] = abstract.SMA(df, 20)
df['WMA'] = abstract.WMA(df, 20)
df['EMA'] = abstract.EMA(df, 20)
df['DEMA'] = abstract.DEMA(df, 20)
df['TEMA'] = abstract.TEMA(df, 20)

df

,open,high,low,close,volume,SMA,WMA,EMA,DEMA,TEMA
Date,,,,,,,,,,
2020-01-02,74.059998,75.150002,73.797501,74.207466,135480400,NaN,NaN,NaN,NaN,NaN
2020-01-03,74.287498,75.144997,74.125000,73.486023,146322800,NaN,NaN,NaN,NaN,NaN
2020-01-06,73.447502,74.989998,73.187500,74.071579,118387200,NaN,NaN,NaN,NaN,NaN
2020-01-07,74.959999,75.224998,74.370003,73.723213,108872000,NaN,NaN,NaN,NaN,NaN
2020-01-08,74.290001,76.110001,74.290001,74.909149,132079200,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2021-05-28,125.570000,125.800003,124.550003,124.610001,71311100,126.740062,126.108905,126.908650,125.658231,124.759762
2021-06-01,125.080002,125.349998,123.940002,124.279999,67637100,126.338300,125.874613,126.658302,125.300466,124.390377
2021-06-02,124.279999,125.239998,124.050003,125.059998,59278900,126.209639,125.752870,126.506083,125.139842,124.308824
2021-06-03,124.680000,124.849998,123.129997,123.540001,76229200,125.992500,125.498618,126.223599,124.731895,123.866508
2021-06-04,124.070000,126.160004,123.849998,125.889999,75087300,125.811000,125.488857,126.191827,124.813445,124.133005

## CALCULATE MOMENTUM INDICATORS

In [129]:
df['RSI'] = abstract.RSI(df, 14)

temp = abstract.MACD(df, fastperiod=12, slowperiod=26)
df['MACD'] = temp['macd']
df['MACD Signal'] = temp['macdsignal']

df['ADX'] = abstract.ADX(df, 14)
df['DI+'] = abstract.PLUS_DI(df, 14)
df['DI-'] = abstract.MINUS_DI(df, 14)

temp = abstract.STOCHF(df, fastk_period=14)
df['Stochastic Oscillator'] = temp['fastk']

df['Williams %R'] = abstract.WILLR(df, 14)

df

,open,high,low,close,volume,SMA,WMA,EMA,DEMA,TEMA,RSI,MACD,MACD Signal,ADX,DI+,DI-,Stochastic Oscillator,Williams %R
Date,,,,,,,,,,,,,,,,,,
2020-01-02,74.059998,75.150002,73.797501,74.207466,135480400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03,74.287498,75.144997,74.125000,73.486023,146322800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-06,73.447502,74.989998,73.187500,74.071579,118387200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-07,74.959999,75.224998,74.370003,73.723213,108872000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-08,74.290001,76.110001,74.290001,74.909149,132079200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-05-28,125.570000,125.800003,124.550003,124.610001,71311100,126.740062,126.108905,126.908650,125.658231,124.759762,42.829580,-0.975433,-0.850684,17.706931,18.248892,25.746294,38.879700,-61.120300
2021-06-01,125.080002,125.349998,123.940002,124.279999,67637100,126.338300,125.874613,126.658302,125.300466,124.390377,42.077660,-1.059934,-0.892534,17.896307,17.507426,26.457993,33.443103,-66.556897
2021-06-02,124.279999,125.239998,124.050003,125.059998,59278900,126.209639,125.752870,126.506083,125.139842,124.308824,44.555366,-1.051837,-0.924394,18.072156,16.883922,25.515725,40.292935,-59.707065
2021-06-03,124.680000,124.849998,123.129997,123.540001,76229200,125.992500,125.498618,126.223599,124.731895,123.866508,40.885064,-1.154759,-0.970467,18.607273,15.895186,26.813020,12.454203,-87.545797
2021-06-04,124.070000,126.160004,123.849998,125.889999,75087300,125.811000,125.488857,126.191827,124.813445,124.133005,48.015056,-1.034773,-0.983329,18.287116,18.584730,24.698524,55.494415,-44.505585

## EXTRACT CLOSING PRICE OF OTHER TICKERS

In [130]:
temp = yf.download('GOOGL', start = start_time, end = end_time)
df['Google Close'] = temp['Adj Close']

[*********************100%***********************]  1 of 1 completed

In [131]:
temp = yf.download('AMZN', start = start_time, end = end_time)
df['Amazon Close'] = temp['Adj Close']

[*********************100%***********************]  1 of 1 completed

In [132]:
temp = yf.download('MSFT', start = start_time, end = end_time)
df['Microsoft Close'] = temp['Adj Close']

[*********************100%***********************]  1 of 1 completed

In [133]:
temp = yf.download('FB', start = start_time, end = end_time)
df['Facebook Close'] = temp['Adj Close']

[*********************100%***********************]  1 of 1 completed

In [134]:
df

,open,high,low,close,volume,SMA,WMA,EMA,DEMA,TEMA,...,MACD Signal,ADX,DI+,DI-,Stochastic Oscillator,Williams %R,Google Close,Amazon Close,Microsoft Close,Facebook Close
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-02,74.059998,75.150002,73.797501,74.207466,135480400,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1368.680054,1898.010010,158.205765,209.779999
2020-01-03,74.287498,75.144997,74.125000,73.486023,146322800,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1361.520020,1874.969971,156.235825,208.669998
2020-01-06,73.447502,74.989998,73.187500,74.071579,118387200,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1397.810059,1902.880005,156.639694,212.600006
2020-01-07,74.959999,75.224998,74.370003,73.723213,108872000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1395.109985,1906.859985,155.211456,213.059998
2020-01-08,74.290001,76.110001,74.290001,74.909149,132079200,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1405.040039,1891.969971,157.683731,215.220001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-05-28,125.570000,125.800003,124.550003,124.610001,71311100,126.740062,126.108905,126.908650,125.658231,124.759762,...,-0.850684,17.706931,18.248892,25.746294,38.879700,-61.120300,2356.850098,3223.070068,249.679993,328.730011
2021-06-01,125.080002,125.349998,123.940002,124.279999,67637100,126.338300,125.874613,126.658302,125.300466,124.390377,...,-0.892534,17.896307,17.507426,26.457993,33.443103,-66.556897,2381.179932,3218.649902,247.399994,329.130005
2021-06-02,124.279999,125.239998,124.050003,125.059998,59278900,126.209639,125.752870,126.506083,125.139842,124.308824,...,-0.924394,18.072156,16.883922,25.515725,40.292935,-59.707065,2370.590088,3233.989990,247.300003,329.149994
2021-06-03,124.680000,124.849998,123.129997,123.540001,76229200,125.992500,125.498618,126.223599,124.731895,123.866508,...,-0.970467,18.607273,15.895186,26.813020,12.454203,-87.545797,2347.580078,3187.010010,245.710007,326.040009
2021-06-04,124.070000,126.160004,123.849998,125.889999,75087300,125.811000,125.488857,126.191827,124.813445,124.133005,...,-0.983329,18.287116,18.584730,24.698524,55.494415,-44.505585,2393.570068,3206.219971,250.789993,330.350006

In [135]:
df =  df.rename(columns={'open': 'Open', 'high': 'High', 'low': 'Low', 'close': 'Target', 'volume': 'Volume'})
df

,Open,High,Low,Target,Volume,SMA,WMA,EMA,DEMA,TEMA,...,MACD Signal,ADX,DI+,DI-,Stochastic Oscillator,Williams %R,Google Close,Amazon Close,Microsoft Close,Facebook Close
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-02,74.059998,75.150002,73.797501,74.207466,135480400,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1368.680054,1898.010010,158.205765,209.779999
2020-01-03,74.287498,75.144997,74.125000,73.486023,146322800,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1361.520020,1874.969971,156.235825,208.669998
2020-01-06,73.447502,74.989998,73.187500,74.071579,118387200,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1397.810059,1902.880005,156.639694,212.600006
2020-01-07,74.959999,75.224998,74.370003,73.723213,108872000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1395.109985,1906.859985,155.211456,213.059998
2020-01-08,74.290001,76.110001,74.290001,74.909149,132079200,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1405.040039,1891.969971,157.683731,215.220001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-05-28,125.570000,125.800003,124.550003,124.610001,71311100,126.740062,126.108905,126.908650,125.658231,124.759762,...,-0.850684,17.706931,18.248892,25.746294,38.879700,-61.120300,2356.850098,3223.070068,249.679993,328.730011
2021-06-01,125.080002,125.349998,123.940002,124.279999,67637100,126.338300,125.874613,126.658302,125.300466,124.390377,...,-0.892534,17.896307,17.507426,26.457993,33.443103,-66.556897,2381.179932,3218.649902,247.399994,329.130005
2021-06-02,124.279999,125.239998,124.050003,125.059998,59278900,126.209639,125.752870,126.506083,125.139842,124.308824,...,-0.924394,18.072156,16.883922,25.515725,40.292935,-59.707065,2370.590088,3233.989990,247.300003,329.149994
2021-06-03,124.680000,124.849998,123.129997,123.540001,76229200,125.992500,125.498618,126.223599,124.731895,123.866508,...,-0.970467,18.607273,15.895186,26.813020,12.454203,-87.545797,2347.580078,3187.010010,245.710007,326.040009
2021-06-04,124.070000,126.160004,123.849998,125.889999,75087300,125.811000,125.488857,126.191827,124.813445,124.133005,...,-0.983329,18.287116,18.584730,24.698524,55.494415,-44.505585,2393.570068,3206.219971,250.789993,330.350006

## CALCULATE RETURNS OF TARGET VARIABLE AND OTHER TICKERS

In [136]:
df['Returns Target'] = (df['Target']/df['Target'].shift(1)) - 1

In [137]:
df['Returns Google'] = (df['Google Close']/df['Google Close'].shift(1)) - 1

In [138]:
df['Returns Amazon'] = (df['Amazon Close']/df['Amazon Close'].shift(1)) - 1

In [139]:
df['Returns Microsoft'] = (df['Microsoft Close']/df['Microsoft Close'].shift(1)) - 1

In [140]:
df['Returns Facebook'] = (df['Facebook Close']/df['Facebook Close'].shift(1)) - 1

In [141]:
df

,Open,High,Low,Target,Volume,SMA,WMA,EMA,DEMA,TEMA,...,Williams %R,Google Close,Amazon Close,Microsoft Close,Facebook Close,Returns Target,Returns Google,Returns Amazon,Returns Microsoft,Returns Facebook
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-02,74.059998,75.150002,73.797501,74.207466,135480400,NaN,NaN,NaN,NaN,NaN,...,NaN,1368.680054,1898.010010,158.205765,209.779999,NaN,NaN,NaN,NaN,NaN
2020-01-03,74.287498,75.144997,74.125000,73.486023,146322800,NaN,NaN,NaN,NaN,NaN,...,NaN,1361.520020,1874.969971,156.235825,208.669998,-0.009722,-0.005231,-0.012139,-0.012452,-0.005291
2020-01-06,73.447502,74.989998,73.187500,74.071579,118387200,NaN,NaN,NaN,NaN,NaN,...,NaN,1397.810059,1902.880005,156.639694,212.600006,0.007968,0.026654,0.014886,0.002585,0.018834
2020-01-07,74.959999,75.224998,74.370003,73.723213,108872000,NaN,NaN,NaN,NaN,NaN,...,NaN,1395.109985,1906.859985,155.211456,213.059998,-0.004703,-0.001932,0.002092,-0.009118,0.002164
2020-01-08,74.290001,76.110001,74.290001,74.909149,132079200,NaN,NaN,NaN,NaN,NaN,...,NaN,1405.040039,1891.969971,157.683731,215.220001,0.016086,0.007118,-0.007809,0.015928,0.010138
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-05-28,125.570000,125.800003,124.550003,124.610001,71311100,126.740062,126.108905,126.908650,125.658231,124.759762,...,-61.120300,2356.850098,3223.070068,249.679993,328.730011,-0.005348,-0.002467,-0.002180,0.001484,-0.012081
2021-06-01,125.080002,125.349998,123.940002,124.279999,67637100,126.338300,125.874613,126.658302,125.300466,124.390377,...,-66.556897,2381.179932,3218.649902,247.399994,329.130005,-0.002648,0.010323,-0.001371,-0.009132,0.001217
2021-06-02,124.279999,125.239998,124.050003,125.059998,59278900,126.209639,125.752870,126.506083,125.139842,124.308824,...,-59.707065,2370.590088,3233.989990,247.300003,329.149994,0.006276,-0.004447,0.004766,-0.000404,0.000061
2021-06-03,124.680000,124.849998,123.129997,123.540001,76229200,125.992500,125.498618,126.223599,124.731895,123.866508,...,-87.545797,2347.580078,3187.010010,245.710007,326.040009,-0.012154,-0.009706,-0.014527,-0.006429,-0.009449
2021-06-04,124.070000,126.160004,123.849998,125.889999,75087300,125.811000,125.488857,126.191827,124.813445,124.133005,...,-44.505585,2393.570068,3206.219971,250.789993,330.350006,0.019022,0.019590,0.006028,0.020675,0.013219

## CALCULATE VOLUME CHANGE

In [142]:
df['Volume Change'] = df['Volume']/df['Volume'].shift(1)

In [143]:
df

,Open,High,Low,Target,Volume,SMA,WMA,EMA,DEMA,TEMA,...,Google Close,Amazon Close,Microsoft Close,Facebook Close,Returns Target,Returns Google,Returns Amazon,Returns Microsoft,Returns Facebook,Volume Change
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-02,74.059998,75.150002,73.797501,74.207466,135480400,NaN,NaN,NaN,NaN,NaN,...,1368.680054,1898.010010,158.205765,209.779999,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03,74.287498,75.144997,74.125000,73.486023,146322800,NaN,NaN,NaN,NaN,NaN,...,1361.520020,1874.969971,156.235825,208.669998,-0.009722,-0.005231,-0.012139,-0.012452,-0.005291,1.080029
2020-01-06,73.447502,74.989998,73.187500,74.071579,118387200,NaN,NaN,NaN,NaN,NaN,...,1397.810059,1902.880005,156.639694,212.600006,0.007968,0.026654,0.014886,0.002585,0.018834,0.809082
2020-01-07,74.959999,75.224998,74.370003,73.723213,108872000,NaN,NaN,NaN,NaN,NaN,...,1395.109985,1906.859985,155.211456,213.059998,-0.004703,-0.001932,0.002092,-0.009118,0.002164,0.919626
2020-01-08,74.290001,76.110001,74.290001,74.909149,132079200,NaN,NaN,NaN,NaN,NaN,...,1405.040039,1891.969971,157.683731,215.220001,0.016086,0.007118,-0.007809,0.015928,0.010138,1.213160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-05-28,125.570000,125.800003,124.550003,124.610001,71311100,126.740062,126.108905,126.908650,125.658231,124.759762,...,2356.850098,3223.070068,249.679993,328.730011,-0.005348,-0.002467,-0.002180,0.001484,-0.012081,0.753613
2021-06-01,125.080002,125.349998,123.940002,124.279999,67637100,126.338300,125.874613,126.658302,125.300466,124.390377,...,2381.179932,3218.649902,247.399994,329.130005,-0.002648,0.010323,-0.001371,-0.009132,0.001217,0.948479
2021-06-02,124.279999,125.239998,124.050003,125.059998,59278900,126.209639,125.752870,126.506083,125.139842,124.308824,...,2370.590088,3233.989990,247.300003,329.149994,0.006276,-0.004447,0.004766,-0.000404,0.000061,0.876426
2021-06-03,124.680000,124.849998,123.129997,123.540001,76229200,125.992500,125.498618,126.223599,124.731895,123.866508,...,2347.580078,3187.010010,245.710007,326.040009,-0.012154,-0.009706,-0.014527,-0.006429,-0.009449,1.285942
2021-06-04,124.070000,126.160004,123.849998,125.889999,75087300,125.811000,125.488857,126.191827,124.813445,124.133005,...,2393.570068,3206.219971,250.789993,330.350006,0.019022,0.019590,0.006028,0.020675,0.013219,0.985020

## DROPS UNNECESSARY ROWS AND COLUMNS

In [144]:
df = df.dropna() 
df

,Open,High,Low,Target,Volume,SMA,WMA,EMA,DEMA,TEMA,...,Google Close,Amazon Close,Microsoft Close,Facebook Close,Returns Target,Returns Google,Returns Amazon,Returns Microsoft,Returns Facebook,Volume Change
Date,,,,,,,,,,,,,,,,,,,,,
2020-03-25,62.687500,64.562500,61.075001,60.804588,303602000,65.695430,63.126933,65.001349,59.369853,58.104843,...,1101.619995,1885.839966,145.106949,156.210007,-0.005509,-0.025124,-0.027968,-0.009573,-0.029631,1.055892
2020-03-26,61.630001,64.669998,61.590000,64.004311,252087200,65.508697,62.965874,64.906393,59.725317,58.988308,...,1162.920044,1955.489990,154.183533,163.339996,0.052623,0.055645,0.036933,0.062551,0.045644,0.830321
2020-03-27,63.187500,63.967499,61.762501,61.354385,204216800,65.191450,62.570226,64.568107,59.574398,59.077102,...,1110.260010,1900.099976,147.852631,156.789993,-0.041402,-0.045283,-0.028325,-0.041061,-0.040100,0.810104
2020-03-30,62.685001,63.880001,62.349998,63.105312,167976400,64.646605,62.371546,64.428793,59.784630,59.650951,...,1146.310059,1963.949951,158.252686,165.949997,0.028538,0.032470,0.033603,0.070341,0.058422,0.822540
2020-03-31,63.900002,65.622498,63.000000,62.976532,197002000,64.212835,62.212491,64.290482,59.963482,60.129492,...,1161.949951,1949.719971,155.763794,166.800003,-0.002041,0.013644,-0.007246,-0.015727,0.005122,1.172796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-05-28,125.570000,125.800003,124.550003,124.610001,71311100,126.740062,126.108905,126.908650,125.658231,124.759762,...,2356.850098,3223.070068,249.679993,328.730011,-0.005348,-0.002467,-0.002180,0.001484,-0.012081,0.753613
2021-06-01,125.080002,125.349998,123.940002,124.279999,67637100,126.338300,125.874613,126.658302,125.300466,124.390377,...,2381.179932,3218.649902,247.399994,329.130005,-0.002648,0.010323,-0.001371,-0.009132,0.001217,0.948479
2021-06-02,124.279999,125.239998,124.050003,125.059998,59278900,126.209639,125.752870,126.506083,125.139842,124.308824,...,2370.590088,3233.989990,247.300003,329.149994,0.006276,-0.004447,0.004766,-0.000404,0.000061,0.876426
2021-06-03,124.680000,124.849998,123.129997,123.540001,76229200,125.992500,125.498618,126.223599,124.731895,123.866508,...,2347.580078,3187.010010,245.710007,326.040009,-0.012154,-0.009706,-0.014527,-0.006429,-0.009449,1.285942
2021-06-04,124.070000,126.160004,123.849998,125.889999,75087300,125.811000,125.488857,126.191827,124.813445,124.133005,...,2393.570068,3206.219971,250.789993,330.350006,0.019022,0.019590,0.006028,0.020675,0.013219,0.985020

In [145]:
df = df.drop(['Open', 'High', 'Low', 'Volume'], axis = 1)
df

,Target,SMA,WMA,EMA,DEMA,TEMA,RSI,MACD,MACD Signal,ADX,...,Google Close,Amazon Close,Microsoft Close,Facebook Close,Returns Target,Returns Google,Returns Amazon,Returns Microsoft,Returns Facebook,Volume Change
Date,,,,,,,,,,,,,,,,,,,,,
2020-03-25,60.804588,65.695430,63.126933,65.001349,59.369853,58.104843,42.254529,-4.265413,-3.821977,33.601922,...,1101.619995,1885.839966,145.106949,156.210007,-0.005509,-0.025124,-0.027968,-0.009573,-0.029631,1.055892
2020-03-26,64.004311,65.508697,62.965874,64.906393,59.725317,58.988308,46.700154,-3.813760,-3.820333,32.614001,...,1162.920044,1955.489990,154.183533,163.339996,0.052623,0.055645,0.036933,0.062551,0.045644,0.830321
2020-03-27,61.354385,65.191450,62.570226,64.568107,59.574398,59.077102,43.699620,-3.627829,-3.781833,31.696645,...,1110.260010,1900.099976,147.852631,156.789993,-0.041402,-0.045283,-0.028325,-0.041061,-0.040100,0.810104
2020-03-30,63.105312,64.646605,62.371546,64.428793,59.784630,59.650951,46.161096,-3.301138,-3.685694,30.844815,...,1146.310059,1963.949951,158.252686,165.949997,0.028538,0.032470,0.033603,0.070341,0.058422,0.822540
2020-03-31,62.976532,64.212835,62.212491,64.290482,59.963482,60.129492,46.001792,-3.017838,-3.552122,29.473088,...,1161.949951,1949.719971,155.763794,166.800003,-0.002041,0.013644,-0.007246,-0.015727,0.005122,1.172796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-05-28,124.610001,126.740062,126.108905,126.908650,125.658231,124.759762,42.829580,-0.975433,-0.850684,17.706931,...,2356.850098,3223.070068,249.679993,328.730011,-0.005348,-0.002467,-0.002180,0.001484,-0.012081,0.753613
2021-06-01,124.279999,126.338300,125.874613,126.658302,125.300466,124.390377,42.077660,-1.059934,-0.892534,17.896307,...,2381.179932,3218.649902,247.399994,329.130005,-0.002648,0.010323,-0.001371,-0.009132,0.001217,0.948479
2021-06-02,125.059998,126.209639,125.752870,126.506083,125.139842,124.308824,44.555366,-1.051837,-0.924394,18.072156,...,2370.590088,3233.989990,247.300003,329.149994,0.006276,-0.004447,0.004766,-0.000404,0.000061,0.876426
2021-06-03,123.540001,125.992500,125.498618,126.223599,124.731895,123.866508,40.885064,-1.154759,-0.970467,18.607273,...,2347.580078,3187.010010,245.710007,326.040009,-0.012154,-0.009706,-0.014527,-0.006429,-0.009449,1.285942
2021-06-04,125.889999,125.811000,125.488857,126.191827,124.813445,124.133005,48.015056,-1.034773,-0.983329,18.287116,...,2393.570068,3206.219971,250.789993,330.350006,0.019022,0.019590,0.006028,0.020675,0.013219,0.985020