In [1]:
import talib as ta
import numpy as np
import pandas as pd
import yfinance as yf
from talib import MA_Type
from datetime import date
from talib import abstract

## DOWNLOAD HISTORICAL STOCK DATA FOR INFOSYS

In [2]:
ticker = 'INFY'
start_time = '2020-01-02'
today = date.today()
end_time = today.strftime("%Y-%m-%d")

In [3]:
df = pd.DataFrame()
df = yf.download(ticker, start = start_time, end = end_time)

df.head()

[*********************100%***********************]  1 of 1 completed

             Open   High    Low  Close  Adj Close    Volume
Date
2020-01-02  10.30  10.34  10.23  10.29   9.935719   5688000
2020-01-03  10.29  10.35  10.26  10.31   9.955031   6992200
2020-01-06  10.22  10.25  10.17  10.21   9.858474  10068900
2020-01-07  10.12  10.17  10.10  10.10   9.752262  10589100
2020-01-08  10.00  10.12   9.99  10.09   9.742607  13440400

In [4]:
df =  df.rename(columns={'Open': 'open', 'High': 'high', 'Low': 'low', 'Adj Close': 'close', 'Volume': 'volume'})
df = df.drop(['Close'], axis='columns')
df

                 open       high        low      close    volume
Date
2020-01-02  10.300000  10.340000  10.230000   9.935719   5688000
2020-01-03  10.290000  10.350000  10.260000   9.955031   6992200
2020-01-06  10.220000  10.250000  10.170000   9.858474  10068900
2020-01-07  10.120000  10.170000  10.100000   9.752262  10589100
2020-01-08  10.000000  10.120000   9.990000   9.742607  13440400
...               ...        ...        ...        ...       ...
2021-06-07  19.290001  19.480000  19.219999  19.400000  10765100
2021-06-08  19.580000  19.650000  19.389999  19.500000   7916900
2021-06-09  19.500000  19.700001  19.500000  19.660000   4972800
2021-06-10  19.780001  19.910000  19.719999  19.889999   6716400
2021-06-11  19.990000  20.549999  19.920000  20.540001  14076000

[364 rows x 5 columns]

## CALCULATION OF BOLLINGER BANDS

In [5]:
temp = abstract.BBANDS(df, matype=0)

df['upper_band'] = temp['upperband']
df['lower_band'] = temp['lowerband']

df

,open,high,low,close,volume,upper_band,lower_band
Date,,,,,,,
2020-01-02,10.300000,10.340000,10.230000,9.935719,5688000,NaN,NaN
2020-01-03,10.290000,10.350000,10.260000,9.955031,6992200,NaN,NaN
2020-01-06,10.220000,10.250000,10.170000,9.858474,10068900,NaN,NaN
2020-01-07,10.120000,10.170000,10.100000,9.752262,10589100,NaN,NaN
2020-01-08,10.000000,10.120000,9.990000,9.742607,13440400,10.026651,9.670987
...,...,...,...,...,...,...,...
2021-06-07,19.290001,19.480000,19.219999,19.400000,10765100,19.443602,19.112398
2021-06-08,19.580000,19.650000,19.389999,19.500000,7916900,19.565529,19.082472
2021-06-09,19.500000,19.700001,19.500000,19.660000,4972800,19.752717,19.043283
2021-06-10,19.780001,19.910000,19.719999,19.889999,6716400,19.967790,19.128210
2021-06-11,19.990000,20.549999,19.920000,20.540001,14076000,20.610542,18.985457

## CALCULATION MOVING AVERAGES

In [6]:
df['SMA_5'] = abstract.SMA(df, 5)
df['SMA_10'] = abstract.SMA(df, 10)
df['SMA_15'] = abstract.SMA(df, 15)
df['SMA_20'] = abstract.SMA(df, 20)

df['WMA_5'] = abstract.WMA(df, 5)
df['WMA_10'] = abstract.WMA(df, 10)
df['WMA_15'] = abstract.WMA(df, 15)
df['WMA_20'] = abstract.WMA(df, 20)

df['EMA_5'] = abstract.EMA(df, 5)
df['EMA_10'] = abstract.EMA(df, 10)
df['EMA_15'] = abstract.EMA(df, 15)
df['EMA_20'] = abstract.EMA(df, 20)

df['DEMA_5'] = abstract.DEMA(df, 5)
df['DEMA_10'] = abstract.DEMA(df, 10)
df['DEMA_15'] = abstract.DEMA(df, 15)
df['DEMA_20'] = abstract.DEMA(df, 20)

df['TEMA_5'] = abstract.TEMA(df, 5)
df['TEMA_10'] = abstract.TEMA(df, 10)
df['TEMA_15'] = abstract.TEMA(df, 15)
df['TEMA_20'] = abstract.TEMA(df, 20)

df

,open,high,low,close,volume,upper_band,lower_band,SMA_5,SMA_10,SMA_15,...,EMA_15,EMA_20,DEMA_5,DEMA_10,DEMA_15,DEMA_20,TEMA_5,TEMA_10,TEMA_15,TEMA_20
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-02,10.300000,10.340000,10.230000,9.935719,5688000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03,10.290000,10.350000,10.260000,9.955031,6992200,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-06,10.220000,10.250000,10.170000,9.858474,10068900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-07,10.120000,10.170000,10.100000,9.752262,10589100,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-08,10.000000,10.120000,9.990000,9.742607,13440400,10.026651,9.670987,9.848819,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-07,19.290001,19.480000,19.219999,19.400000,10765100,19.443602,19.112398,19.278000,19.097497,18.817505,...,18.908392,18.783970,19.394360,19.414668,19.315946,19.183985,19.362374,19.462844,19.494197,19.429062
2021-06-08,19.580000,19.650000,19.389999,19.500000,7916900,19.565529,19.082472,19.324000,19.199775,18.918679,...,18.982343,18.852163,19.482137,19.493209,19.403660,19.275780,19.466768,19.533861,19.571672,19.518871
2021-06-09,19.500000,19.700001,19.500000,19.660000,4972800,19.752717,19.043283,19.398000,19.312114,19.024581,...,19.067050,18.929100,19.612023,19.598902,19.509821,19.381982,19.617769,19.643272,19.675604,19.628399
2021-06-10,19.780001,19.910000,19.719999,19.889999,6716400,19.967790,19.128210,19.548000,19.395000,19.133941,...,19.169918,19.020614,19.802858,19.747709,19.647353,19.513163,19.835736,19.809882,19.822744,19.772001
2021-06-11,19.990000,20.549999,19.920000,20.540001,14076000,20.610542,18.985457,19.798000,19.532000,19.272779,...,19.341179,19.165318,20.258468,20.066903,19.908787,19.741880,20.374231,20.203790,20.141156,20.052078

## CALCULATION OF MOMENTUM INDICATORS

In [7]:
df['RSI'] = abstract.RSI(df, 14)

temp = abstract.MACD(df, fastperiod=12, slowperiod=26)
df['MACD'] = temp['macd']
df['MACD Signal'] = temp['macdsignal']

df['ADX'] = abstract.ADX(df, 14)
df['DI+'] = abstract.PLUS_DI(df, 14)
df['DI-'] = abstract.MINUS_DI(df, 14)

temp = abstract.STOCHF(df, fastk_period=14)
df['Stochastic Oscillator'] = temp['fastk']

df['Williams %R'] = abstract.WILLR(df, 14)

df

,open,high,low,close,volume,upper_band,lower_band,SMA_5,SMA_10,SMA_15,...,TEMA_15,TEMA_20,RSI,MACD,MACD Signal,ADX,DI+,DI-,Stochastic Oscillator,Williams %R
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-02,10.300000,10.340000,10.230000,9.935719,5688000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03,10.290000,10.350000,10.260000,9.955031,6992200,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-06,10.220000,10.250000,10.170000,9.858474,10068900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-07,10.120000,10.170000,10.100000,9.752262,10589100,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-08,10.000000,10.120000,9.990000,9.742607,13440400,10.026651,9.670987,9.848819,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-07,19.290001,19.480000,19.219999,19.400000,10765100,19.443602,19.112398,19.278000,19.097497,18.817505,...,19.494197,19.429062,67.679371,0.325635,0.236308,18.045842,27.420005,15.022610,93.846156,-6.153844
2021-06-08,19.580000,19.650000,19.389999,19.500000,7916900,19.565529,19.082472,19.324000,19.199775,18.918679,...,19.571672,19.518871,69.160901,0.341082,0.257263,19.260041,29.511742,14.194908,89.795940,-10.204060
2021-06-09,19.500000,19.700001,19.500000,19.660000,4972800,19.752717,19.043283,19.398000,19.312114,19.024581,...,19.675604,19.628399,71.418364,0.362062,0.278222,20.505562,29.314824,13.575295,96.850323,-3.149677
2021-06-10,19.780001,19.910000,19.719999,19.889999,6716400,19.967790,19.128210,19.548000,19.395000,19.133941,...,19.822744,19.772001,74.327591,0.392720,0.301122,22.128764,32.349764,12.821883,98.461502,-1.538498
2021-06-11,19.990000,20.549999,19.920000,20.540001,14076000,20.610542,18.985457,19.798000,19.532000,19.272779,...,20.141156,20.052078,80.399548,0.464116,0.333721,24.662005,41.156384,11.074472,99.484622,-0.515378

In [8]:
df =  df.rename(columns={'open': 'Open', 'high': 'High', 'low': 'Low', 'close': 'Close', 'volume': 'Volume'})
df

,Open,High,Low,Close,Volume,upper_band,lower_band,SMA_5,SMA_10,SMA_15,...,TEMA_15,TEMA_20,RSI,MACD,MACD Signal,ADX,DI+,DI-,Stochastic Oscillator,Williams %R
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-02,10.300000,10.340000,10.230000,9.935719,5688000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03,10.290000,10.350000,10.260000,9.955031,6992200,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-06,10.220000,10.250000,10.170000,9.858474,10068900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-07,10.120000,10.170000,10.100000,9.752262,10589100,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-08,10.000000,10.120000,9.990000,9.742607,13440400,10.026651,9.670987,9.848819,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-07,19.290001,19.480000,19.219999,19.400000,10765100,19.443602,19.112398,19.278000,19.097497,18.817505,...,19.494197,19.429062,67.679371,0.325635,0.236308,18.045842,27.420005,15.022610,93.846156,-6.153844
2021-06-08,19.580000,19.650000,19.389999,19.500000,7916900,19.565529,19.082472,19.324000,19.199775,18.918679,...,19.571672,19.518871,69.160901,0.341082,0.257263,19.260041,29.511742,14.194908,89.795940,-10.204060
2021-06-09,19.500000,19.700001,19.500000,19.660000,4972800,19.752717,19.043283,19.398000,19.312114,19.024581,...,19.675604,19.628399,71.418364,0.362062,0.278222,20.505562,29.314824,13.575295,96.850323,-3.149677
2021-06-10,19.780001,19.910000,19.719999,19.889999,6716400,19.967790,19.128210,19.548000,19.395000,19.133941,...,19.822744,19.772001,74.327591,0.392720,0.301122,22.128764,32.349764,12.821883,98.461502,-1.538498
2021-06-11,19.990000,20.549999,19.920000,20.540001,14076000,20.610542,18.985457,19.798000,19.532000,19.272779,...,20.141156,20.052078,80.399548,0.464116,0.333721,24.662005,41.156384,11.074472,99.484622,-0.515378

## CALCULATION OF LAGGED CLOSING PRICES OF TARGET VARIABLE

In [9]:
df['close_1'] = df['Close'].shift(1)
df['close_2'] = df['Close'].shift(2)
df['close_5'] = df['Close'].shift(5)

df

,Open,High,Low,Close,Volume,upper_band,lower_band,SMA_5,SMA_10,SMA_15,...,MACD,MACD Signal,ADX,DI+,DI-,Stochastic Oscillator,Williams %R,close_1,close_2,close_5
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-02,10.300000,10.340000,10.230000,9.935719,5688000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03,10.290000,10.350000,10.260000,9.955031,6992200,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.935719,NaN,NaN
2020-01-06,10.220000,10.250000,10.170000,9.858474,10068900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.955031,9.935719,NaN
2020-01-07,10.120000,10.170000,10.100000,9.752262,10589100,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.858474,9.955031,NaN
2020-01-08,10.000000,10.120000,9.990000,9.742607,13440400,10.026651,9.670987,9.848819,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.752262,9.858474,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-07,19.290001,19.480000,19.219999,19.400000,10765100,19.443602,19.112398,19.278000,19.097497,18.817505,...,0.325635,0.236308,18.045842,27.420005,15.022610,93.846156,-6.153844,19.290001,19.139999,19.340000
2021-06-08,19.580000,19.650000,19.389999,19.500000,7916900,19.565529,19.082472,19.324000,19.199775,18.918679,...,0.341082,0.257263,19.260041,29.511742,14.194908,89.795940,-10.204060,19.400000,19.290001,19.270000
2021-06-09,19.500000,19.700001,19.500000,19.660000,4972800,19.752717,19.043283,19.398000,19.312114,19.024581,...,0.362062,0.278222,20.505562,29.314824,13.575295,96.850323,-3.149677,19.500000,19.400000,19.290001
2021-06-10,19.780001,19.910000,19.719999,19.889999,6716400,19.967790,19.128210,19.548000,19.395000,19.133941,...,0.392720,0.301122,22.128764,32.349764,12.821883,98.461502,-1.538498,19.660000,19.500000,19.139999
2021-06-11,19.990000,20.549999,19.920000,20.540001,14076000,20.610542,18.985457,19.798000,19.532000,19.272779,...,0.464116,0.333721,24.662005,41.156384,11.074472,99.484622,-0.515378,19.889999,19.660000,19.290001

## CALCULATION OF DIFFERENCE OF CLOSING PRICE wrt PAST

In [10]:
df['diff_1'] = df['Close'] - df['Close'].shift(1)
df['diff_2'] = df['Close'] - df['Close'].shift(2)
df['diff_5'] = df['Close'] - df['Close'].shift(5)

df

,Open,High,Low,Close,Volume,upper_band,lower_band,SMA_5,SMA_10,SMA_15,...,DI+,DI-,Stochastic Oscillator,Williams %R,close_1,close_2,close_5,diff_1,diff_2,diff_5
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-02,10.300000,10.340000,10.230000,9.935719,5688000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03,10.290000,10.350000,10.260000,9.955031,6992200,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,9.935719,NaN,NaN,0.019312,NaN,NaN
2020-01-06,10.220000,10.250000,10.170000,9.858474,10068900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,9.955031,9.935719,NaN,-0.096558,-0.077246,NaN
2020-01-07,10.120000,10.170000,10.100000,9.752262,10589100,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,9.858474,9.955031,NaN,-0.106212,-0.202769,NaN
2020-01-08,10.000000,10.120000,9.990000,9.742607,13440400,10.026651,9.670987,9.848819,NaN,NaN,...,NaN,NaN,NaN,NaN,9.752262,9.858474,NaN,-0.009655,-0.115867,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-07,19.290001,19.480000,19.219999,19.400000,10765100,19.443602,19.112398,19.278000,19.097497,18.817505,...,27.420005,15.022610,93.846156,-6.153844,19.290001,19.139999,19.340000,0.109999,0.260000,0.059999
2021-06-08,19.580000,19.650000,19.389999,19.500000,7916900,19.565529,19.082472,19.324000,19.199775,18.918679,...,29.511742,14.194908,89.795940,-10.204060,19.400000,19.290001,19.270000,0.100000,0.209999,0.230000
2021-06-09,19.500000,19.700001,19.500000,19.660000,4972800,19.752717,19.043283,19.398000,19.312114,19.024581,...,29.314824,13.575295,96.850323,-3.149677,19.500000,19.400000,19.290001,0.160000,0.260000,0.369999
2021-06-10,19.780001,19.910000,19.719999,19.889999,6716400,19.967790,19.128210,19.548000,19.395000,19.133941,...,32.349764,12.821883,98.461502,-1.538498,19.660000,19.500000,19.139999,0.230000,0.389999,0.750000
2021-06-11,19.990000,20.549999,19.920000,20.540001,14076000,20.610542,18.985457,19.798000,19.532000,19.272779,...,41.156384,11.074472,99.484622,-0.515378,19.889999,19.660000,19.290001,0.650002,0.880001,1.250000

## CALCULATION OF RETURNS

In [11]:
df['returns_1'] = (df['Close']/df['Close'].shift(1)) - 1
df['returns_2'] = (df['Close']/df['Close'].shift(2)) - 1
df['returns_5'] = (df['Close']/df['Close'].shift(5)) - 1

df

,Open,High,Low,Close,Volume,upper_band,lower_band,SMA_5,SMA_10,SMA_15,...,Williams %R,close_1,close_2,close_5,diff_1,diff_2,diff_5,returns_1,returns_2,returns_5
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-02,10.300000,10.340000,10.230000,9.935719,5688000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03,10.290000,10.350000,10.260000,9.955031,6992200,NaN,NaN,NaN,NaN,NaN,...,NaN,9.935719,NaN,NaN,0.019312,NaN,NaN,0.001944,NaN,NaN
2020-01-06,10.220000,10.250000,10.170000,9.858474,10068900,NaN,NaN,NaN,NaN,NaN,...,NaN,9.955031,9.935719,NaN,-0.096558,-0.077246,NaN,-0.009699,-0.007775,NaN
2020-01-07,10.120000,10.170000,10.100000,9.752262,10589100,NaN,NaN,NaN,NaN,NaN,...,NaN,9.858474,9.955031,NaN,-0.106212,-0.202769,NaN,-0.010774,-0.020369,NaN
2020-01-08,10.000000,10.120000,9.990000,9.742607,13440400,10.026651,9.670987,9.848819,NaN,NaN,...,NaN,9.752262,9.858474,NaN,-0.009655,-0.115867,NaN,-0.000990,-0.011753,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-07,19.290001,19.480000,19.219999,19.400000,10765100,19.443602,19.112398,19.278000,19.097497,18.817505,...,-6.153844,19.290001,19.139999,19.340000,0.109999,0.260000,0.059999,0.005702,0.013584,0.003102
2021-06-08,19.580000,19.650000,19.389999,19.500000,7916900,19.565529,19.082472,19.324000,19.199775,18.918679,...,-10.204060,19.400000,19.290001,19.270000,0.100000,0.209999,0.230000,0.005155,0.010886,0.011936
2021-06-09,19.500000,19.700001,19.500000,19.660000,4972800,19.752717,19.043283,19.398000,19.312114,19.024581,...,-3.149677,19.500000,19.400000,19.290001,0.160000,0.260000,0.369999,0.008205,0.013402,0.019181
2021-06-10,19.780001,19.910000,19.719999,19.889999,6716400,19.967790,19.128210,19.548000,19.395000,19.133941,...,-1.538498,19.660000,19.500000,19.139999,0.230000,0.389999,0.750000,0.011699,0.020000,0.039185
2021-06-11,19.990000,20.549999,19.920000,20.540001,14076000,20.610542,18.985457,19.798000,19.532000,19.272779,...,-0.515378,19.889999,19.660000,19.290001,0.650002,0.880001,1.250000,0.032680,0.044761,0.064800

## CALCULATION OF VOLUME CHANGE

In [12]:
df['volume_change_1'] = (df['Volume']/df['Volume'].shift(1)) - 1
df['volume_change_2'] = (df['Volume']/df['Volume'].shift(2)) - 1
df['volume_change_5'] = (df['Volume']/df['Volume'].shift(5)) - 1

df

,Open,High,Low,Close,Volume,upper_band,lower_band,SMA_5,SMA_10,SMA_15,...,close_5,diff_1,diff_2,diff_5,returns_1,returns_2,returns_5,volume_change_1,volume_change_2,volume_change_5
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-02,10.300000,10.340000,10.230000,9.935719,5688000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03,10.290000,10.350000,10.260000,9.955031,6992200,NaN,NaN,NaN,NaN,NaN,...,NaN,0.019312,NaN,NaN,0.001944,NaN,NaN,0.229290,NaN,NaN
2020-01-06,10.220000,10.250000,10.170000,9.858474,10068900,NaN,NaN,NaN,NaN,NaN,...,NaN,-0.096558,-0.077246,NaN,-0.009699,-0.007775,NaN,0.440019,0.770200,NaN
2020-01-07,10.120000,10.170000,10.100000,9.752262,10589100,NaN,NaN,NaN,NaN,NaN,...,NaN,-0.106212,-0.202769,NaN,-0.010774,-0.020369,NaN,0.051664,0.514416,NaN
2020-01-08,10.000000,10.120000,9.990000,9.742607,13440400,10.026651,9.670987,9.848819,NaN,NaN,...,NaN,-0.009655,-0.115867,NaN,-0.000990,-0.011753,NaN,0.269267,0.334843,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-07,19.290001,19.480000,19.219999,19.400000,10765100,19.443602,19.112398,19.278000,19.097497,18.817505,...,19.340000,0.109999,0.260000,0.059999,0.005702,0.013584,0.003102,0.660256,0.847325,4.003765
2021-06-08,19.580000,19.650000,19.389999,19.500000,7916900,19.565529,19.082472,19.324000,19.199775,18.918679,...,19.270000,0.100000,0.209999,0.230000,0.005155,0.010886,0.011936,-0.264577,0.220990,-0.130708
2021-06-09,19.500000,19.700001,19.500000,19.660000,4972800,19.752717,19.043283,19.398000,19.312114,19.024581,...,19.290001,0.160000,0.260000,0.369999,0.008205,0.013402,0.019181,-0.371875,-0.538063,-0.277881
2021-06-10,19.780001,19.910000,19.719999,19.889999,6716400,19.967790,19.128210,19.548000,19.395000,19.133941,...,19.139999,0.230000,0.389999,0.750000,0.011699,0.020000,0.039185,0.350627,-0.151638,0.152555
2021-06-11,19.990000,20.549999,19.920000,20.540001,14076000,20.610542,18.985457,19.798000,19.532000,19.272779,...,19.290001,0.650002,0.880001,1.250000,0.032680,0.044761,0.064800,1.095766,1.830598,1.170882

## EXTRACT CLOSING PRICES OF TCS

In [13]:
temp = yf.download('TCS', start = start_time, end = end_time)
df['close_TCS'] = temp['Adj Close']

df['returns_TCS'] = (df['close_TCS']/df['close_TCS'].shift(1)) - 1

df

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Volume,upper_band,lower_band,SMA_5,SMA_10,SMA_15,...,diff_2,diff_5,returns_1,returns_2,returns_5,volume_change_1,volume_change_2,volume_change_5,close_TCS,returns_TCS
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-02,10.300000,10.340000,10.230000,9.935719,5688000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.991522,NaN
2020-01-03,10.290000,10.350000,10.260000,9.955031,6992200,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.001944,NaN,NaN,0.229290,NaN,NaN,4.000870,0.002342
2020-01-06,10.220000,10.250000,10.170000,9.858474,10068900,NaN,NaN,NaN,NaN,NaN,...,-0.077246,NaN,-0.009699,-0.007775,NaN,0.440019,0.770200,NaN,4.159782,0.039720
2020-01-07,10.120000,10.170000,10.100000,9.752262,10589100,NaN,NaN,NaN,NaN,NaN,...,-0.202769,NaN,-0.010774,-0.020369,NaN,0.051664,0.514416,NaN,4.103695,-0.013483
2020-01-08,10.000000,10.120000,9.990000,9.742607,13440400,10.026651,9.670987,9.848819,NaN,NaN,...,-0.115867,NaN,-0.000990,-0.011753,NaN,0.269267,0.334843,NaN,4.056957,-0.011389
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-07,19.290001,19.480000,19.219999,19.400000,10765100,19.443602,19.112398,19.278000,19.097497,18.817505,...,0.260000,0.059999,0.005702,0.013584,0.003102,0.660256,0.847325,4.003765,13.500000,0.034483
2021-06-08,19.580000,19.650000,19.389999,19.500000,7916900,19.565529,19.082472,19.324000,19.199775,18.918679,...,0.209999,0.230000,0.005155,0.010886,0.011936,-0.264577,0.220990,-0.130708,13.860000,0.026667
2021-06-09,19.500000,19.700001,19.500000,19.660000,4972800,19.752717,19.043283,19.398000,19.312114,19.024581,...,0.260000,0.369999,0.008205,0.013402,0.019181,-0.371875,-0.538063,-0.277881,13.820000,-0.002886
2021-06-10,19.780001,19.910000,19.719999,19.889999,6716400,19.967790,19.128210,19.548000,19.395000,19.133941,...,0.389999,0.750000,0.011699,0.020000,0.039185,0.350627,-0.151638,0.152555,13.630000,-0.013748
2021-06-11,19.990000,20.549999,19.920000,20.540001,14076000,20.610542,18.985457,19.798000,19.532000,19.272779,...,0.880001,1.250000,0.032680,0.044761,0.064800,1.095766,1.830598,1.170882,13.850000,0.016141

In [14]:
save_path = r'C:\Data\Stock Market\stock_market_features.csv'

df.to_csv(save_path)